### ISSUE TITLE
por casualidad sabes donde puedo descargar un sistema php puro y mysql para factura electronica dian

### ISSUE THREAD

**Issue by henrypandales** [rolandopalermo/andrea-jaxb-ubl-20#1]
Como puedo usar este sistema para implementarlo en mi pos php mysql 

me puedes escribir al wsapp +57 314 775 4208 mil bendiciones

**Comment by rolandopalermo** [comment]
Hola Henry, por ahora la única manera sería que lo integres a través de llamadas REST

**Comment by henrypandales** [comment]
eso quiero tener mi propia api pero aun no se como hacerlo sin necesidad  de usar laravel ni composer

**Comment by henrypandales** [comment]
que costo tiene esta api?

**Comment by rolandopalermo** [comment]
Te dejo mi correo para poder platicar: support@rolandopalermo.com
